language: generic
cache:
  directories:
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/target
    - $HOME/docker/

matrix:
  include:
    - os: linux
      env:
        - TARGET=armv7-unknown-linux-gnueabihf
        - NAME=arm7hf
        - EXT=tar.gz
      addons:
        apt:
          packages: &armhf
          - gcc-arm-linux-gnueabihf
          - libc6-armhf-cross
          - libc6-dev-armhf-cross
    - os: linux
      env:
        - TARGET=x86_64-unknown-linux-musl
        - NAME=linux64
        - EXT=tar.gz
      dist: trusty
      sudo: required
      addons:
        apt:
          packages:
          - musl-tools
          - libbz2-dev
    - os: linux
      env:
        - TARGET=i686-unknown-linux-musl
        - NAME=linux32
        - EXT=tar.gz
      dist: trusty
      sudo: required
      addons:
        apt:
          packages: &i686
          - musl-tools
          - gcc-multilib
          - libbz2-dev
    - os: linux
      env:
        - TARGET=x86_64-pc-windows-gnu
        - NAME=win64
        - EXT=zip
      dist: trusty
      sudo: required
      addons:
        apt:
          packages:
          - gcc-mingw-w64-x86-64
          - binutils-mingw-w64-x86-64
          - libbz2-dev
    - os: linux
      env:
        - TARGET=i686-pc-windows-gnu
        - NAME=win32
        - EXT=zip
        - TOOLCHAIN=nightly
        - DOCKER_IMAGE=i686-trusty
      dist: trusty
      services:
        - docker
    - os: osx
      env:
        - TARGET=x86_64-apple-darwin
        - NAME=macos
        - EXT=tar.gz

script:
  - bash ci.sh

deploy:
  provider: releases
  api_key:
    secure:
      sWyBW1/vfptM4euavS4rhY7lBCJKFN0YurVv4MYRIGTLGuSM/P7UZYaIFG1dWIdoUAU+8Ix66hBRLcGkOh0gTl0hgKA7IeAdPLr/B2vYR/Aqmi0e90y4zY2FchVVOZn9xEVs9vsZ8M8hbIBSFMqY30AoYz/h+OgtVMqrD2/5Ef7U0ChFk95bIgvZMJO6uiBbe5G+cOghWQZMamy3+GO9ubCBi3nnCJRrmySrxPqFeNKQCzE/00zA5eU3re5GhExcufIjdUw1bSENt4brdd4TSvjXDnz+21mJoHguGI9X32nqYfaeoISjMcU5L4X4yTDrv9MAvZbeZHpggc9oBWELAMXqGKt4TX48xrQPR6XwIWFxgkpr04gZbWNqy9Ei4Q7njw8s/WOm6I06z85hjsKLbeM6Qa++bxJCHpZvisTQbUMHIkx3sAxV4/YX0r78nCGVIV4UnY6Y4b+HEMYyseuFnTy3ymNz+kCJpcALaI+GAklmcui8raUZTelSVWe4Qg/BoHAktU05E0szHivwolaoFsVqjB8WXfgSfmw9t6NoRrIjlVd+AN2Y22L+kgZbxCXbH1jR820Jmyk8pESC9gVs9qvNJPVJ6scu7a40G/KKH+3iEQ0nfJSaO6EVxMA0FtE/AoHXqB7L5upgm8z5RaMb4ysxWYP3ZUjFBLFHpFsnuUk=
  skip_cleanup: true
  file:
    - "geckodriver-$TRAVIS_TAG-$NAME.$EXT"
  on:
    tags: true
    repo: ckm2k1/geckodriver
    condition: -n "$NAME"
