language: generic
cache:
  directories:
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/target
    - $HOME/docker/

matrix:
  include:
    - os: linux
      env:
        - TARGET=armv7-unknown-linux-gnueabihf
        - NAME=arm7hf
        - EXT=tar.gz
      addons:
        apt:
          packages: &armhf
          - gcc-arm-linux-gnueabihf
          - libc6-armhf-cross
          - libc6-dev-armhf-cross
    - os: linux
      env:
        - TARGET=x86_64-unknown-linux-musl
        - NAME=linux64
        - EXT=tar.gz
      dist: trusty
      sudo: required
      addons:
        apt:
          packages:
          - musl-tools
          - libbz2-dev
    - os: linux
      env:
        - TARGET=i686-unknown-linux-musl
        - NAME=linux32
        - EXT=tar.gz
      dist: trusty
      sudo: required
      addons:
        apt:
          packages: &i686
          - musl-tools
          - gcc-multilib
          - libbz2-dev
    - os: linux
      env:
        - TARGET=x86_64-pc-windows-gnu
        - NAME=win64
        - EXT=zip
      dist: trusty
      sudo: required
      addons:
        apt:
          packages:
          - gcc-mingw-w64-x86-64
          - binutils-mingw-w64-x86-64
          - libbz2-dev
    - os: linux
      env:
        - TARGET=i686-pc-windows-gnu
        - NAME=win32
        - EXT=zip
        - TOOLCHAIN=nightly
        - DOCKER_IMAGE=i686-trusty
      dist: trusty
      services:
        - docker
    - os: osx
      env:
        - TARGET=x86_64-apple-darwin
        - NAME=macos
        - EXT=tar.gz

script:
  - bash ci.sh

deploy:
  provider: releases
  api_key:
    secure:
      EKMPRPLd0NnWftZ5WYNV+vdpwhh1tTYxTrSThgqVWC41rgkGejnDLYxtygdS6+8MZh5aLH82c3RQTsY48T/vQQNdvfmNMJYL8q1z5frDwwGCfB6vugMPE+AlIOjdX2mIUXFKiTAB8dsUntp6n9PndOmpeNeu5bNjCFvxZ3OEm0rvxHtCXindO2vq8KHeTU4h5+2PVzJ3BvonkK5zBHmo+KUIagYkCudxZQlFjgN6SdHbpPOumVy3HYo196LdpHyuXNiBiKtctJXAlJKDsEX0UKIF2u8xVnod5A3WuGbZ1RRoNuazMKgto9WGEtyvVGeWQFoVpKYn/OTP8pp1wHiABxK/1LF5zFKg/n1Ogr83qvPX6aT6BbfMtxVHs9iIwlNvdRNfciaBSSpkpS/OsFphU6k3l21AncWzXnPqqvxpmcuZ1X8yp8GI08McVoQ5Td+hWM2D/7Smjq1lEV2DTyGGx+WXw1xZzgClc8ocJQUa8G7P51TVbWSqkNUruQX6mG4XJ915OBuEg+KfEtL3/N3pwhYUVeZs4R4bshn4dPYteVos5cALhs+EsDbQgtRUDRsLOEa1opa+7gMOR/GWqNibnEUlYBvwtDKYPTPr/rrzcVQZj0c+v8pnppNYyIhHCLNnmSAPWBwGB14N4VghORxeYwYeV0X6iWBCwCvGWoksZJQ=
  skip_cleanup: true
  file:
    - "geckodriver-$TRAVIS_TAG-$NAME.$EXT"
  on:
    tags: true
    repo: ckm2k1/geckodriver
    condition: -n "$NAME"
